# nodeLinker: node-modules
nodeLinker: pnp

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.1.1.cjs
